### ISSUE TITLE
It doesn't save column title

### ISSUE THREAD

**Issue by rezarms** [microsoft/vsts-extension-retrospectives#90] opened 2020-12-07 09:59 UTC
The latest version broke our Retro.
When we add new column and change the title it doesn't save the title and just shows New Column.

**Comment by polatengin** [comment] 2020-12-07 10:08
I received a similar report , as a workaround, please hit `ENTER` when you set the name for a column. it'll be saved.

I'll fix this issue ASAP.

**Comment by oliveratgithub** [comment] 2020-12-07 10:33
I had the same pitfall (#89) until I figured you now have to confirm with `Return` 🙈

**Comment by roel4ez** [comment] 2020-12-09 09:58
duplicate of #91 

Indeed, pressing <enter> or <tab> it works.

**Closed** 2021-01-07 05:50 UTC
