### ISSUE TITLE
Retrospective Loading in Azure on premise

### ISSUE THREAD

**Issue by NidiaAlvarez** [microsoft/vsts-extension-retrospectives#393] opened 2022-07-15 18:56 UTC
We have Azure DevOps on premise 2019, since the new version was installed for retrospectives, in all projects does not load and only appear a message ...loading

**Comment by gt66stang** [comment] 2022-07-18 13:30
We have ADO 2019 and the latest update also has our retrospective board just spinning with .... Loading.  Can we get a fix updated on this issue?

**Comment by polatengin** [comment] 2022-07-27 00:21
hi @NidiaAlvarez , @gt66stang 

with release v1.80.10 and v1.80.11 this issue must be fixed.

can I kindly ask you to double check your extension version, if it didn't update automatically, update it manually and see the issue is fixed, please?

closing this issue for now, please feel free to re-open it, if you see the issue is persist on your environment.

**Closed by polatengin** 2022-07-27 00:21 UTC
