### ISSUE TITLE
1.92.31 (Latest) Version crashes on load "We detected an error in the application"

### ISSUE THREAD

**Issue by JJKW1984** [microsoft/vsts-extension-retrospectives#957] opened 2024-11-19 19:22 UTC
**Describe the bug**
When we open the URL: https://dev.azure.com/OURORG/OURPROJECT/_apps/hub/ms-devlabs.team-retrospectives.home the web app crashes and an errors is played on the page: We detected an error in the application

**Are you using the Retrospectives Tool on-prem?**
[ ] Yes
[ X] No

If Yes, what version of the extension?

**To Reproduce**

1. Go to 'Azure Board'
2. Click on 'Retrospectives'
3. See error
![Image](https://github.com/user-attachments/assets/25659b7b-2cde-468e-8075-9b12978166db)

OR 
1. Navigate to "https://dev.azure.com/meijervsts/edo-eqe/_apps/hub/ms-devlabs.team-retrospectives.home"
2. See error
5. See error

**Expected behavior**
The board hub application should load

**Screenshots**
![Image](https://github.com/user-attachments/assets/b234abe6-7919-4ddc-8c10-eadb920eef6a)

**What screen type are you seeing this on ?**
[X ] Desktop
[] Mobile

**Additional context**
This started with the last update 1.92.31 which was upload to our environment today.
We have cleared the cache and get the same error.
We have tried in an incognito window and get the same error.
We have tested this in two different ADO orgs and get the same error.

ADO Version
About Azure DevOps Service
Version Dev19.M247.1 (AzureDevOps_M247_20241113.6)

**Comment by yirkha** [comment] 2024-11-19 19:52
Duplicate of #956, let's consolidate the discussion there

**Closed** 2024-11-19 20:46 UTC
Labels: bug
