### ISSUE TITLE
Latest update is resulting in "We detected an error in the application"

### ISSUE THREAD

**Issue by sachinjain-gh** [microsoft/vsts-extension-retrospectives#958] opened 2024-11-19 19:46 UTC
**Describe the bug**
When you load retrospective in Azure DevOps Service, it states "We detected an error in the application" 

**Are you using the Retrospectives Tool on-prem?**
[ ] Yes
[x] No

If Yes, what version of the extension?
N/A

**To Reproduce**
Navigate to retrospectives within Boards and it errors with above message.

**Expected behavior**
It should just load fine.

**Screenshots**
![Image](https://github.com/user-attachments/assets/13bc7402-7cd5-45dd-8b70-99d1f395f056)

**What screen type are you seeing this on ?**
[x] Desktop
[ ] Mobile

**Additional context**
None

**Comment by yirkha** [comment] 2024-11-19 19:53
Duplicate of #956, let's consolidate the discussion there

**Comment by roshanrad599** [comment] 2024-11-19 20:21
Yes same here, with on premise DevOps 2020, after the update this afternoon, the retrospective board no longer loads with the error "We detected an error in the application"

Latest updated version: 1.92.31

**Comment by agaray-fdot** [comment] 2024-11-19 21:18
Cross posting from Developer Community feedback for visibility to MS. 

We are also receiving the same error as mentioned above. 

“We detected an error in the application”

The Retrospective extension immediately fails to load and the error above is displayed.

Extension Details:

Retrospectives Marketplace Link - https://marketplace.visualstudio.com/items?itemName=ms-devlabs.team-retrospectives&targetId=9c115251-2dbf-4e0a-b81b-e3cda76eaddb&utm_source=vstsproduct&utm_medium=ExtHubManageList
Version: 1.92.31 (Latest)
Last Updated: Nov 19, 2024 at 12:45 PM EST (3 hrs ago)

**Comment by polatengin** [comment] 2024-11-19 21:55
I'm sorry to hear `react-toastify` update causes issues.

I just reverted the update back, waiting for tests to finish, I'll update the extension on the public marketplace 👍

**Closed** 2024-11-19 22:23 UTC
Labels: bug

**Comment by plynch99** [comment] 2024-12-02 05:59
We are also seeing this issue on one of our ADO boards.
