### ISSUE TITLE
Unable to change the text for 3rd column when setting up a retrospectives board

### ISSUE THREAD

**Issue by mullenlj3** [microsoft/vsts-extension-retrospectives#102] opened 2020-12-16 19:03 UTC
Love this product, however I noticed that I used to be able to add 3 columns on my retro board. When I add my 3rd now and save, it reverts back t' "New Column". Thanks!

**Comment by polatengin** [comment] 2020-12-16 19:39
hi @mullenlj3 , this is duplicate of #90 . closing this and tracking the original issue.

PS : if you hit ENTER when you change the column title, it'll be saved

**Closed by polatengin** 2020-12-16 19:39 UTC
