### ISSUE TITLE
Retrospectives Tool takes too long to load

### ISSUE THREAD

**Issue by yayitserica** [microsoft/vsts-extension-retrospectives#38] opened 2020-07-08 14:47 UTC
![image](https://user-images.githubusercontent.com/15487798/86933155-3f0df580-c108-11ea-9f6f-5ddff8a5ce32.png)

This issue occurs for me in more than one ADO organization, sometimes taking ~10 minutes to load.

**Comment by polatengin** [comment] 2020-07-08 14:54
I saw this message from other customers too. it seems moving to new sdk will help solving this issue.

because old sdk is jquery and jqueryui based and new sdk is not, it'll help to trim more KBs

ref: [Extension development](https://developer.microsoft.com/en-us/azure-devops/develop/extensions)

**Comment by polatengin** [comment] 2020-07-08 14:56
#31 is related to this issue, I'd like to have a reference to it

**Comment by mpth** [comment] 2020-07-13 18:29
While moving to the new SDK will have a positive effect on the extensions load time I doubt it is the cause for load times >10min that some have reported. 

I would think that the backend possibly has very long response times sometimes.

**Comment by polatengin** [comment] 2020-07-13 18:31
hmm, I think we should have ~5 seconds timeout to backend requests. if it's not responding in around 5 seconds, we should skip it. very good suggestion @mpth thanks!...

**Comment by mpth** [comment] 2020-07-13 19:14
Just guessing though. I think you should see proof in AppInsights if dependency tracking is enabled on the client (it is by default)

**Comment by david2764** [comment] 2020-07-29 14:22
We found that Google Chrome is blocking mixed content delivered by http and https with our on-prem installation.  

We re-enabled mixed content delivery through the browser options.  We would happily turn off http on the Azure DevOps server, but we are concerned about how this would affect the ~200 developers that we support, and their link to Visual Studio.

**Comment by HappyFlow** [comment] 2020-07-30 07:02
As Retrospectives are essential to Agile teams I would suggest in taking up the code of it and put it in the core of ADO.

**Comment by polatengin** [comment] 2020-07-30 16:38
maybe one day core team will add our code into AzDO (hopefully! 😊)

**Comment by hildo** [comment] 2021-02-11 06:15
I get this every two weeks.  I attempt to load Retrospectives, and it says it's taking too long to load.  I see this in by browser's console when it happens

![image](https://user-images.githubusercontent.com/1204224/107607150-25c3bd80-6c84-11eb-92ee-939be3a0d751.png)

If I go away for a day and try again, then something loads.  But, if I don't prime the pump, so to speak, a day before our team's retro, the tool just doesn't load. 

Comments about browsers blocking requests I think is a red herring, as the page will load a day later.

**Comment by polatengin** [comment] 2024-09-25 22:39
I think I fixed this issue long time ago, please feel free to reopen it if you think it still takes long time to load

**Closed by polatengin** 2024-09-25 22:39 UTC
Labels: v1.5
