### ISSUE TITLE
If Retrospective board gets deleted by another admin, when I get back to the tool I get stuck in a blank page until I "clear the visit history"

### ISSUE THREAD

**Issue by fgutiyama** [microsoft/vsts-extension-retrospectives#56] opened 2020-08-20 13:26 UTC
Steps to reproduce:

1. Create a board
2. Leave the app with that board open
3. Ask some other admin to delete that board
4. Load the app
5. Start page will be blank and will only show tabs with no navigation options

![image](https://user-images.githubusercontent.com/48068716/90775298-0fd5d100-e2cf-11ea-8452-21458b97fe89.png)

6. Clear visit history and start page will work again

**Comment by polatengin** [comment] 2020-11-26 10:25
hey @fgutiyama, I couldn't reproduce this issue. It seems that the extension is loading next board from the list if it can't find the requested board.

can you double check it, please?

**Comment by polatengin** [comment] 2020-12-07 09:54
since I couldn't reproduce it and there is no interaction, I'm closing this issue.

please feel free to re-open it , if you need further assistance.

**Closed by polatengin** 2020-12-07 09:54 UTC
