### ISSUE TITLE
Azure DevOps 2020 support?

### ISSUE THREAD

**Issue by japj** [microsoft/vsts-extension-retrospectives#77] opened 2020-12-02 14:43 UTC
We are preparing to upgrade from Azure DevOps 2019 to 2020.
However, it seems the Retrospective extension does not (yet) work with 2020 (it only shows "Loading").

https://marketplace.visualstudio.com/items?itemName=ms-devlabs.team-retrospectives shows only 2018/2019 is supported.

Since there seems to be (recent) activity in this repo I was wondering what the state of Azure DevOps 2020 support is.

**Comment by japj** [comment] 2020-12-04 11:11
@polatengin it seems v1.0.47 actually works on Azure DevOps Server 2020

The previous data (IT uninstalled 1.0.45 yesterday since it was not working yet) was actually still present, so I did not need to manually download/upload data (perhaps there is some "delete retention" in the server for the dataService.

I did notice that the background color of the cards has changed to gray, making the yellow "> 2 Items" a bit less readable
(previously this was white background)

![image](https://user-images.githubusercontent.com/512/101156931-a2ee0900-3629-11eb-8c70-f09941a7028b.png)

**Comment by polatengin** [comment] 2020-12-05 19:15
@japj as we discussed offline, extension supports Azure DevOps Server 2020.

also, with the latest fixes (PR #83) contrast issue should be fixed.

I'm closing this issue, please don't hesitate to re-open it if you feel that the problem isn't fixed.

**Closed** 2020-12-06 09:34 UTC
